### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [cyrusstoller/cyrusstoller.github.io#10]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`setting-up-my-new-laptop.html`](https://github.com/cyrusstoller/cyrusstoller.github.io/blob/967a30e83bccecaa0486ac0597a18adde36e1de5/2014/07/16/setting-up-my-new-laptop.html). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by cyrusstoller** [comment]
Thanks for letting me know! It should be updated now.
